### ISSUE TITLE
Need clarification on units for Numerical Propagation

### ISSUE THREAD

**Issue by isConic** [catrujilla/pyDHM#5]
Angular spectrum is described as:  

> angularSpectrum(field, z, wavelength, dx, dy)

> Function to propagate a complex distribution using the angular spectrum approach. field is the input complex wavefield to be propagated. The distance to propagate the input wavefield is represented by z. wavelength is the wavelength of the illumination source used to record the hologram. Finally, dx and dy are the pixel size for the input and output planes along the x- and y- directions.
  
Is this **z**,  **dx** and **dy** distance in meters? millimeters?

**Comment by catrujilla** [comment]
The units for z, dx, and dy in the angular spectrum function are not explicitly specified in the library. However, based on the standard units used in optics and imaging, meters are commonly used for these variables. Therefore, it would be reasonable to assume that the units for z, dx, and dy are in meters.

However, it is essential to note that the units used for z, dx, and dy depend on the specific application and the conventions used in that field. As long as you keep the units consistent throughout your code, there will not be a problem with the selected units.

**Comment by isConic** [comment]
Thank you!
